### PR TITLE
Add Core Options. (check please)

### PR DESCRIPTION
**Pull request by Tatsuya79**
Please check the video part (widescreen/hires/fps) as I'm not sure I did that right.
Particularly the fps change will cause sound issue if you can fix that (need to set the frequency/fps ratio accordingly).

I left the in-game menu untouched, so if you go there and change stuff it will be different from the core options and won't be saved.

### CODE REVIEW

**Comment by Tatsuya79** [comment]
mmm Time Trial crashes, wait... it's not me it seems, it crashes with current version too.

It crashes if you don't do "play game" before launching the time trial, unrelated to this commit.

**Comment by Tatsuya79** [comment]
In more details everything should work fine except:

-cannonball_video_fps: completely wrong outside of "Smooth (60)", even after a restart. 
I couldn't get that right.

-cannonball_video_widescreen & cannonball_video_hires 
Lose the background if changed during a race (clouds, distant mountains,etc). 
It will be displayed again on track change or if you go into the menu and do "play game" again.

**Comment by inactive123** [comment]
Let me know if this can be merged or not.

**Comment by Tatsuya79** [comment]
Yes, you can merge it. 
I commented out the fps part which is just wrong.
Everything else is working from the core options side, it would just need to be improved as described above.

**Pull request merged**
